### ISSUE TITLE
another unexpected error occurred

### ISSUE THREAD

**Issue by DimEvil** [inbo/vlaams-biodiversiteitsportaal#12]
![image](https://github.com/inbo/vlaams-biodiversiteitsportaal/assets/3965195/9c882a75-339c-4b08-bdc6-d8a7e7db0046)

url: https://collections.biodiversiteitsportaal.dev.svdev.be/collection/editCollection

*An unexpected error has occurred. If this is the first time this page has appeared, try the refresh button in your browser. 
If this fails, try to return to the [home page](https://collections.biodiversiteitsportaal.dev.svdev.be/collectory) and start again. 
If this page is still displayed, please report the incident to LA Flanders support. [Click here to email LA Flanders support](https://collections.biodiversiteitsportaal.dev.svdev.be/collection/editCollection#). The following is useful information that helps us discover what has happened. Please copy it into emails requesting support. You might also like to expand the more detailed information by clicking on 'Show stack trace' and copying that text to us as well.
Thanks for your patience.*

`Error 500: could not execute statement; SQL [n/a]; nested exception is org.hibernate.exception.DataException: could not execute statement
Servlet: grailsDispatcherServlet
URI: /collection/editCollection
Exception Message: could not execute statement; SQL [n/a]; nested exception is org.hibernate.exception.DataException: could not execute statement
Caused by: could not execute statement; SQL [n/a]; nested exception is org.hibernate.exception.DataException: could not execute statement
Class: AbstractHibernateGormInstanceApi
At Line: [250]`

       org.springframework.dao.DataIntegrityViolationException: could not execute statement; SQL [n/a]; nested exception is 
        org.hibernate.exception.DataException: could not execute statement

	at org.springframework.orm.hibernate5.SessionFactoryUtils.convertHibernateAccessException(SessionFactoryUtils.java:216)

	at org.grails.orm.hibernate.GrailsHibernateTemplate.doExecute(GrailsHibernateTemplate.java:305)

	at org.grails.orm.hibernate.GrailsHibernateTemplate.execute(GrailsHibernateTemplate.java:241)

	at org.grails.orm.hibernate.GrailsHibernateTemplate.execute(GrailsHibernateTemplate.java:120)

	at org.grails.orm.hibernate.AbstractHibernateGormInstanceApi.performSave(AbstractHibernateGormInstanceApi.groovy:247)´

**Comment by DimEvil** [comment]
probably due to decimalLongitude & decimalLatitude
